version: '3.8'

services:
  app:
    build: .
    expose:
      - "80"
    environment:
      DB_HOST: zekubw4fjelwjqlrepe23ilj
      DB_PORT: "3306"
      DB_NAME: zumardb
      DB_USER: zumardbuser
      DB_PASS: ${ZUMAR_DB_PASS:-Zf#wI6NxUGW6ROoc4vkGLdZ9e!}
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
    name: coolify
