<?php

function zumar_f($name, $type, $so, $en, $required = false, $extra = array())
{
    return array_merge(array(
        'name' => $name,
        'type' => $type,
        'label_so' => $so,
        'label_en' => $en,
        'required' => $required,
    ), $extra);
}

function zumar_modules()
{
    static $modules = null;
    if ($modules !== null) {
        return $modules;
    }

    $yesNo = array('1' => 'Yes', '0' => 'No');

    $modules = array(
        'countries' => array(
            'table' => 'zf_countries',
            'title_so' => 'Waddamada',
            'title_en' => 'Countries',
            'icon' => 'fa fa-globe',
            'list' => array('country_code', 'country_name', 'currency', 'timezone'),
            'fields' => array(
                zumar_f('country_code', 'text', 'Koodhka waddanka', 'Country code', true),
                zumar_f('country_name', 'text', 'Magaca waddanka', 'Country name', true),
                zumar_f('currency', 'text', 'Lacagta', 'Currency', true),
                zumar_f('timezone', 'text', 'Waqtiga', 'Timezone', true),
            ),
        ),
        'locations' => array(
            'table' => 'zf_locations',
            'title_so' => 'Goobaha',
            'title_en' => 'Locations',
            'icon' => 'fa fa-map-marker',
            'code_field' => 'location_code',
            'code_type' => 'location',
            'list' => array('location_code', 'country_code', 'region_state', 'district', 'gps_coordinates'),
            'fields' => array(
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('region_state', 'text', 'Gobolka / State', 'Region / State'),
                zumar_f('district', 'text', 'Degmada', 'District', true),
                zumar_f('gps_coordinates', 'text', 'GPS', 'GPS coordinates'),
            ),
        ),
        'sectors' => array(
            'table' => 'zf_sectors',
            'title_so' => 'Qaybaha',
            'title_en' => 'Sectors',
            'icon' => 'fa fa-th-large',
            'list' => array('sector_code', 'sector_name', 'sector_lead_role', 'linked_sdgs'),
            'fields' => array(
                zumar_f('sector_code', 'text', 'Koodhka qaybta', 'Sector code', true),
                zumar_f('sector_name', 'text', 'Magaca qaybta', 'Sector name', true),
                zumar_f('sector_lead_role', 'text', 'Doorka hoggaanka', 'Sector lead role'),
                zumar_f('linked_sdgs', 'text', 'SDG-yada', 'Linked SDGs'),
            ),
        ),
        'partners' => array(
            'table' => 'zf_partners',
            'title_so' => 'Lammaanayaasha',
            'title_en' => 'Partners',
            'icon' => 'fa fa-handshake',
            'code_field' => 'partner_code',
            'code_type' => 'partner',
            'list' => array('partner_code', 'partner_name', 'partner_type', 'relationship', 'status'),
            'fields' => array(
                zumar_f('partner_name', 'text', 'Magaca', 'Partner name', true),
                zumar_f('partner_type', 'select', 'Nooca', 'Partner type', true, array('options' => array('Donor' => 'Donor', 'Accreditation Body' => 'Accreditation Body', 'Membership Network' => 'Membership Network'))),
                zumar_f('relationship', 'select', 'Xiriirka', 'Relationship', true, array('options' => array('Funding Partner' => 'Funding Partner', 'Regulatory Accreditation' => 'Regulatory Accreditation', 'Network Membership' => 'Network Membership'))),
                zumar_f('country_of_registration', 'text', 'Waddanka diiwaangelinta', 'Country of registration'),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Active' => 'Active', 'Lapsed' => 'Lapsed', 'Under Renewal' => 'Under Renewal'))),
                zumar_f('notes', 'textarea', 'Qoraal', 'Notes'),
            ),
        ),
        'projects' => array(
            'table' => 'zf_projects',
            'title_so' => 'Mashruucyada',
            'title_en' => 'Projects',
            'icon' => 'fa fa-folder-open',
            'code_field' => 'project_code',
            'code_type' => 'project',
            'list' => array('project_code', 'project_name', 'country_code', 'sector_code', 'year', 'status'),
            'fields' => array(
                zumar_f('project_name', 'text', 'Magaca mashruuca', 'Project name', true),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('sector_code', 'fk', 'Qaybta', 'Sector', true, array('fk' => 'sector')),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', false, array('fk' => 'location')),
                zumar_f('year', 'number', 'Sanadka', 'Year', true),
                zumar_f('start_date', 'date', 'Bilowga', 'Start date'),
                zumar_f('end_date', 'date', 'Dhammaadka', 'End date'),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Planned' => 'Planned', 'Active' => 'Active', 'Completed' => 'Completed', 'Suspended' => 'Suspended'))),
                zumar_f('linked_sdgs', 'text', 'SDG-yada', 'Linked SDGs'),
                zumar_f('description', 'textarea', 'Sharaxaad', 'Description'),
            ),
        ),
        'staff' => array(
            'table' => 'zf_staff',
            'title_so' => 'Shaqaalaha',
            'title_en' => 'Staff',
            'icon' => 'fa fa-id-badge',
            'code_field' => 'staff_code',
            'code_type' => 'staff',
            'list' => array('staff_code', 'full_name', 'position', 'country_code', 'employment_status'),
            'fields' => array(
                zumar_f('full_name', 'text', 'Magaca buuxa', 'Full name', true),
                zumar_f('position', 'select', 'Jagada', 'Position', true, array('options' => array(
                    'Executive Director' => 'Executive Director',
                    'Admin & Finance Manager' => 'Admin & Finance Manager',
                    'Program Coordinator' => 'Program Coordinator',
                    'HR Manager' => 'HR Manager',
                    'Operations Manager' => 'Operations Manager',
                    'Finance Expert' => 'Finance Expert',
                    'Chief Accountant' => 'Chief Accountant',
                    'Project Manager' => 'Project Manager',
                    'Field Manager' => 'Field Manager',
                    'Administrator' => 'Administrator',
                    'M&E Officer' => 'M&E Officer',
                    'Procurement Officer' => 'Procurement Officer',
                    'Civil Work Officer' => 'Civil Work Officer',
                ))),
                zumar_f('reports_to', 'fk', 'U wargeliyaa', 'Reports to', false, array('fk' => 'staff')),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('contract_start', 'date', 'Bilowga qandaraaska', 'Contract start', true),
                zumar_f('contract_end', 'date', 'Dhammaadka qandaraaska', 'Contract end'),
                zumar_f('employment_status', 'select', 'Xaaladda shaqada', 'Employment status', true, array('options' => array('Active' => 'Active', 'On leave' => 'On leave', 'Exited' => 'Exited'))),
            ),
        ),
        'orphans' => array(
            'table' => 'zf_orphans',
            'title_so' => 'Diiwaanka agoonta',
            'title_en' => 'Orphan registry',
            'icon' => 'fa fa-child',
            'code_field' => 'orphan_code',
            'code_type' => 'orphan',
            'form_code' => 'ORPH-01',
            'list' => array('orphan_code', 'full_name', 'gender', 'age', 'country_code', 'year_enrolled', 'status'),
            'fields' => array(
                zumar_f('full_name', 'text', 'Magaca buuxa', 'Full name', true),
                zumar_f('gender', 'select', 'Jinsiga', 'Gender', true, array('options' => array('Female' => 'Female', 'Male' => 'Male'))),
                zumar_f('date_of_birth', 'date', 'Taariikhda dhalashada', 'Date of birth'),
                zumar_f('age', 'number', 'Da\'da', 'Age', true),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('year_enrolled', 'number', 'Sanadka diiwaangelinta', 'Year enrolled', true),
                zumar_f('guardian_name', 'text', 'Magaca masuulka', 'Guardian name'),
                zumar_f('photo', 'file', 'Sawirka', 'Photo'),
                zumar_f('photo_caption', 'text', 'Qoraalka sawirka', 'Photo caption'),
                zumar_f('photo_date', 'date', 'Taariikhda sawirka', 'Photo date'),
                zumar_f('photo_gps', 'text', 'GPS sawirka', 'Photo GPS'),
                zumar_f('consent_flag', 'select', 'Oggolaanshaha sawirka', 'Photo consent', true, array('options' => $yesNo)),
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Active' => 'Active', 'Graduated' => 'Graduated', 'Withdrawn' => 'Withdrawn', 'Deceased' => 'Deceased'))),
            ),
        ),
        'orphan-education' => array(
            'table' => 'zf_orphan_education',
            'title_so' => 'Waxbarashada agoonta',
            'title_en' => 'Orphan education status',
            'icon' => 'fa fa-graduation-cap',
            'form_code' => 'ORPH-02',
            'list' => array('orphan_id', 'school_level', 'grade_class', 'attendance_status', 'date_recorded'),
            'fields' => array(
                zumar_f('orphan_id', 'fk', 'Agoonta', 'Orphan', true, array('fk' => 'orphan')),
                zumar_f('school_level', 'select', 'Heerka dugsiga', 'School level', true, array('options' => array('Pre-school' => 'Pre-school', 'Primary' => 'Primary', 'Secondary' => 'Secondary', 'Not enrolled' => 'Not enrolled'))),
                zumar_f('grade_class', 'text', 'Fasalka', 'Grade / class'),
                zumar_f('school_name', 'text', 'Magaca dugsiga', 'School name'),
                zumar_f('attendance_status', 'select', 'Xaadirnimada', 'Attendance', true, array('options' => array('Attending' => 'Attending', 'Dropped out' => 'Dropped out', 'Never enrolled' => 'Never enrolled'))),
                zumar_f('date_recorded', 'date', 'Taariikhda', 'Date recorded', true),
            ),
        ),
        'orphan-support' => array(
            'table' => 'zf_orphan_support',
            'title_so' => 'Taageerada rubuc-sanadka',
            'title_en' => 'Quarterly support tracking',
            'icon' => 'fa fa-heart',
            'form_code' => 'ORPH-02',
            'list' => array('orphan_id', 'quarter', 'support_type', 'support_status', 'amount_disbursed', 'verification_date'),
            'fields' => array(
                zumar_f('orphan_id', 'fk', 'Agoonta', 'Orphan', true, array('fk' => 'orphan')),
                zumar_f('quarter', 'text', 'Rubuc-sanadka', 'Quarter', true),
                zumar_f('support_type', 'text', 'Nooca taageerada', 'Support type', true),
                zumar_f('support_status', 'select', 'Xaaladda taageerada', 'Support status', true, array('options' => array('Provided' => 'Provided', 'Partially provided' => 'Partially provided', 'Missed' => 'Missed'))),
                zumar_f('amount_disbursed', 'money', 'Lacagta la bixiyay', 'Amount disbursed'),
                zumar_f('verified_by', 'fk', 'Xaqiijiyay', 'Verified by', true, array('fk' => 'staff')),
                zumar_f('verification_date', 'date', 'Taariikhda xaqiijinta', 'Verification date', true),
            ),
        ),
        'sponsors' => array(
            'table' => 'zf_sponsors',
            'title_so' => 'Kafaala-qaadayaasha',
            'title_en' => 'Sponsors',
            'icon' => 'fa fa-user',
            'code_field' => 'sponsor_code',
            'code_type' => 'sponsor',
            'list' => array('sponsor_code', 'sponsor_name', 'orphan_id', 'sponsorship_start', 'monthly_amount'),
            'fields' => array(
                zumar_f('sponsor_name', 'text', 'Magaca', 'Sponsor name'),
                zumar_f('orphan_id', 'fk', 'Agoonta', 'Orphan', false, array('fk' => 'orphan')),
                zumar_f('sponsorship_start', 'date', 'Bilowga', 'Sponsorship start'),
                zumar_f('monthly_amount', 'money', 'Lacagta bishii', 'Monthly amount'),
            ),
        ),
        'school-distributions' => array(
            'table' => 'zf_school_distributions',
            'title_so' => 'Qaybinta agabka dugsiga',
            'title_en' => 'School material distribution',
            'icon' => 'fa fa-truck',
            'code_field' => 'distribution_code',
            'code_type' => 'edu_dist',
            'form_code' => 'EDU-01',
            'list' => array('distribution_code', 'school_name', 'distribution_date', 'no_of_students_reached'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('school_name', 'text', 'Magaca dugsiga', 'School name', true),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('distribution_date', 'date', 'Taariikhda qaybinta', 'Distribution date', true),
                zumar_f('items_distributed', 'textarea', 'Agabka la qaybiyay', 'Items distributed', true),
                zumar_f('no_of_students_reached', 'number', 'Ardayda la gaaray', 'Students reached', true),
                zumar_f('girls_count', 'number', 'Gabdhaha', 'Girls'),
                zumar_f('boys_count', 'number', 'Wiilasha', 'Boys'),
                zumar_f('photos', 'file', 'Sawirada', 'Photos'),
                zumar_f('distributed_by', 'fk', 'Qaybiyay', 'Distributed by', true, array('fk' => 'staff')),
            ),
        ),
        'education-items' => array(
            'table' => 'zf_education_items',
            'title_so' => 'Agabka qaybinta',
            'title_en' => 'Education item catalog',
            'icon' => 'fa fa-list',
            'list' => array('distribution_id', 'item_name', 'unit', 'quantity', 'unit_cost'),
            'fields' => array(
                zumar_f('distribution_id', 'fk', 'Qaybinta', 'Distribution', true, array('fk' => 'distribution')),
                zumar_f('item_name', 'select', 'Agabka', 'Item name', true, array('options' => array('School bag' => 'School bag', 'Textbook' => 'Textbook', 'Pen' => 'Pen', 'Notebook' => 'Notebook', 'Uniform' => 'Uniform'))),
                zumar_f('unit', 'text', 'Unugga', 'Unit', true),
                zumar_f('quantity', 'number', 'Tirada', 'Quantity', true),
                zumar_f('unit_cost', 'money', 'Qiimaha unugga', 'Unit cost'),
            ),
        ),
        'scholarships' => array(
            'table' => 'zf_scholarships',
            'title_so' => 'Deeq-waxbarasho',
            'title_en' => 'Scholarships & talent support',
            'icon' => 'fa fa-award',
            'code_field' => 'scholarship_code',
            'code_type' => 'scholarship',
            'list' => array('scholarship_code', 'student_name', 'education_level', 'amount_awarded', 'academic_year'),
            'fields' => array(
                zumar_f('student_name', 'text', 'Magaca ardayga', 'Student name', true),
                zumar_f('is_orphan', 'select', 'Agoon ma tahay?', 'Is orphan', true, array('options' => $yesNo)),
                zumar_f('orphan_id', 'fk', 'Agoonta', 'Orphan', false, array('fk' => 'orphan')),
                zumar_f('education_level', 'select', 'Heerka waxbarashada', 'Education level', true, array('options' => array('Secondary' => 'Secondary', 'Vocational' => 'Vocational', 'University' => 'University'))),
                zumar_f('field_of_talent', 'text', 'Kartida', 'Field of talent'),
                zumar_f('amount_awarded', 'money', 'Lacagta', 'Amount awarded', true),
                zumar_f('academic_year', 'text', 'Sanad dugsiyeedka', 'Academic year', true),
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
            ),
        ),
        'water-points' => array(
            'table' => 'zf_water_points',
            'title_so' => 'Goobaha biyaha',
            'title_en' => 'Water points',
            'icon' => 'fa fa-tint',
            'code_field' => 'water_point_code',
            'code_type' => 'water',
            'form_code' => 'WASH-01',
            'list' => array('water_point_code', 'water_point_type', 'country_code', 'status', 'no_of_beneficiaries'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('water_point_type', 'select', 'Nooca', 'Water point type', true, array('options' => array('Artesian Well (Solar)' => 'Artesian Well (Solar)', 'Handpump Well' => 'Handpump Well'))),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('date_established', 'date', 'Taariikhda dhismaha', 'Date established', true),
                zumar_f('depth_meters', 'number', 'Moolka (mitir)', 'Depth (meters)'),
                zumar_f('estimated_lifespan_years', 'number', 'Cimriga (sano)', 'Estimated lifespan years'),
                zumar_f('no_of_beneficiaries', 'number', 'Ka-faa\'iidaystayaasha', 'Beneficiaries', true),
                zumar_f('households_served', 'number', 'Qoysaska', 'Households served'),
                zumar_f('gps_coordinates', 'text', 'GPS', 'GPS coordinates', true),
                zumar_f('photos', 'file', 'Sawirada', 'Photos'),
                zumar_f('videos', 'file', 'Fiidiyow', 'Videos'),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Functional' => 'Functional', 'Non-functional' => 'Non-functional', 'Under repair' => 'Under repair'))),
            ),
        ),
        'water-maintenance' => array(
            'table' => 'zf_water_maintenance',
            'title_so' => 'Dayactirka biyaha',
            'title_en' => 'Water point maintenance',
            'icon' => 'fa fa-wrench',
            'form_code' => 'WASH-02',
            'list' => array('water_point_id', 'maintenance_date', 'issue_reported', 'cost'),
            'fields' => array(
                zumar_f('water_point_id', 'fk', 'Goobta biyaha', 'Water point', true, array('fk' => 'water_point')),
                zumar_f('maintenance_date', 'date', 'Taariikhda', 'Maintenance date', true),
                zumar_f('issue_reported', 'text', 'Dhibaatada', 'Issue reported'),
                zumar_f('action_taken', 'textarea', 'Tallaabada', 'Action taken', true),
                zumar_f('cost', 'money', 'Kharashka', 'Cost'),
                zumar_f('technician', 'text', 'Farsamayaqaanka', 'Technician'),
            ),
        ),
        'health-visits' => array(
            'table' => 'zf_health_visits',
            'title_so' => 'Boqashooyinka caafimaadka',
            'title_en' => 'Health facility visits',
            'icon' => 'fa fa-hospital',
            'code_field' => 'visit_code',
            'code_type' => 'health_visit',
            'form_code' => 'HLTH-01',
            'list' => array('visit_code', 'facility_type', 'visit_date', 'no_of_patients_seen'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('facility_type', 'select', 'Nooca xarunta', 'Facility type', true, array('options' => array('Fixed Clinic' => 'Fixed Clinic', 'Mobile Health Unit' => 'Mobile Health Unit'))),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('visit_date', 'date', 'Taariikhda', 'Visit date', true),
                zumar_f('services_provided', 'text', 'Adeegyada', 'Services provided', true),
                zumar_f('no_of_patients_seen', 'number', 'Bukaanada', 'Patients seen', true),
                zumar_f('female_count', 'number', 'Dumar', 'Female'),
                zumar_f('male_count', 'number', 'Rag', 'Male'),
                zumar_f('attending_health_worker', 'fk', 'Shaqaalaha caafimaadka', 'Health worker', false, array('fk' => 'staff')),
            ),
        ),
        'maternal-health' => array(
            'table' => 'zf_maternal_health',
            'title_so' => 'Hooyada iyo ilmaha',
            'title_en' => 'Maternal & child health',
            'icon' => 'fa fa-female',
            'list' => array('service_type', 'service_date', 'facility_used'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('service_type', 'select', 'Nooca adeegga', 'Service type', true, array('options' => array('Prenatal care' => 'Prenatal care', 'Safe delivery' => 'Safe delivery', 'Newborn check' => 'Newborn check'))),
                zumar_f('beneficiary_name', 'text', 'Magaca / ID', 'Beneficiary name / ID'),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('service_date', 'date', 'Taariikhda', 'Service date', true),
                zumar_f('facility_used', 'text', 'Xarunta', 'Facility used'),
                zumar_f('outcome_notes', 'textarea', 'Natiijada', 'Outcome notes'),
            ),
        ),
        'disease-control' => array(
            'table' => 'zf_disease_control',
            'title_so' => 'Xakamaynta cudurrada',
            'title_en' => 'Disease control',
            'icon' => 'fa fa-medkit',
            'form_code' => 'HLTH-02',
            'list' => array('disease_focus', 'intervention_type', 'service_date', 'no_of_beneficiaries'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('disease_focus', 'select', 'Cudurka', 'Disease focus', true, array('options' => array('Malaria' => 'Malaria', 'HIV-AIDS' => 'HIV-AIDS', 'TB' => 'TB'))),
                zumar_f('intervention_type', 'text', 'Nooca faragelinta', 'Intervention type', true),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('service_date', 'date', 'Taariikhda', 'Date', true),
                zumar_f('quantity_or_reach', 'number', 'Tirada / gaaritaanka', 'Quantity or reach', true),
                zumar_f('no_of_beneficiaries', 'number', 'Ka-faa\'iidaystayaasha', 'Beneficiaries', true),
            ),
        ),
        'health-campaigns' => array(
            'table' => 'zf_health_campaigns',
            'title_so' => 'Ololeyaal caafimaad',
            'title_en' => 'Health education campaigns',
            'icon' => 'fa fa-bullhorn',
            'list' => array('topic', 'campaign_date', 'no_reached', 'delivery_method'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('topic', 'select', 'Mawduuca', 'Topic', true, array('options' => array('Nutrition' => 'Nutrition', 'Family planning' => 'Family planning', 'Reproductive health' => 'Reproductive health'))),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('campaign_date', 'date', 'Taariikhda', 'Date', true),
                zumar_f('no_reached', 'number', 'Dadka la gaaray', 'People reached', true),
                zumar_f('delivery_method', 'select', 'Habka', 'Delivery method', false, array('options' => array('Community session' => 'Community session', 'Radio' => 'Radio', 'House visits' => 'House visits'))),
            ),
        ),
        'mental-health' => array(
            'table' => 'zf_mental_health',
            'title_so' => 'Caafimaadka maskaxda',
            'title_en' => 'Mental health counseling',
            'icon' => 'fa fa-lock',
            'restricted' => true,
            'list' => array('session_date', 'session_type', 'no_of_beneficiaries'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('session_date', 'date', 'Taariikhda', 'Session date', true),
                zumar_f('session_type', 'select', 'Nooca', 'Session type', true, array('options' => array('Individual counseling' => 'Individual counseling', 'Group session' => 'Group session', 'Referral' => 'Referral'))),
                zumar_f('no_of_beneficiaries', 'number', 'Ka-faa\'iidaystayaasha', 'Beneficiaries', true),
                zumar_f('partner_id', 'fk', 'Lammaanaha', 'Partner provider', false, array('fk' => 'partner')),
                zumar_f('confidentiality_note', 'textarea', 'Qoraal qarsoodi', 'Confidentiality note', true),
            ),
        ),
        'eye-care' => array(
            'table' => 'zf_eye_care',
            'title_so' => 'Daryeelka indhaha',
            'title_en' => 'Eye care services',
            'icon' => 'fa fa-eye',
            'list' => array('service_type', 'service_date', 'no_of_beneficiaries', 'follow_up_required'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('service_type', 'select', 'Nooca', 'Service type', true, array('options' => array('Cataract surgery' => 'Cataract surgery', 'Eye screening' => 'Eye screening', 'Glasses provided' => 'Glasses provided'))),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('service_date', 'date', 'Taariikhda', 'Service date', true),
                zumar_f('no_of_beneficiaries', 'number', 'Ka-faa\'iidaystayaasha', 'Beneficiaries', true),
                zumar_f('follow_up_required', 'select', 'Raadraac loo baahan yahay', 'Follow-up required', false, array('options' => $yesNo)),
            ),
        ),
        'infrastructure' => array(
            'table' => 'zf_infrastructure',
            'title_so' => 'Hantida kaabayaasha',
            'title_en' => 'Infrastructure assets',
            'icon' => 'fa fa-building',
            'code_field' => 'asset_code',
            'code_type' => 'asset',
            'form_code' => 'INFR-01',
            'list' => array('asset_code', 'asset_type', 'country_code', 'status', 'no_of_beneficiaries_estimated'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('asset_type', 'select', 'Nooca', 'Asset type', true, array('options' => array('Mosque' => 'Mosque', 'School' => 'School', 'Health Centre' => 'Health Centre', 'Community Centre' => 'Community Centre'))),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('construction_start_date', 'date', 'Bilowga dhismaha', 'Construction start', true),
                zumar_f('construction_completion_date', 'date', 'Dhammaadka dhismaha', 'Completion date'),
                zumar_f('capacity', 'number', 'Awoodda', 'Capacity'),
                zumar_f('no_of_beneficiaries_estimated', 'number', 'Ka-faa\'iidaystayaasha', 'Estimated beneficiaries', true),
                zumar_f('construction_cost', 'money', 'Kharashka dhismaha', 'Construction cost'),
                zumar_f('gps_coordinates', 'text', 'GPS', 'GPS coordinates', true),
                zumar_f('photos', 'file', 'Sawirada', 'Photos'),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Planned' => 'Planned', 'Under construction' => 'Under construction', 'Completed' => 'Completed', 'Handed over' => 'Handed over'))),
                zumar_f('handover_authority', 'text', 'Loo wareejiyay', 'Handover authority'),
            ),
        ),
        'livelihood-trainings' => array(
            'table' => 'zf_livelihood_trainings',
            'title_so' => 'Tababarro nolosha',
            'title_en' => 'Livelihood trainings',
            'icon' => 'fa fa-users',
            'form_code' => 'LVHD-01',
            'list' => array('training_type', 'specific_skill', 'start_date', 'no_of_participants'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('training_type', 'select', 'Nooca tababarka', 'Training type', true, array('options' => array('Skills training' => 'Skills training', 'Agriculture & agribusiness' => 'Agriculture & agribusiness', 'Vocational training' => 'Vocational training'))),
                zumar_f('specific_skill', 'text', 'Xirfadda', 'Specific skill'),
                zumar_f('target_group', 'select', 'Kooxda', 'Target group', false, array('options' => array('Women' => 'Women', 'Youth' => 'Youth', 'Mixed' => 'Mixed'))),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('start_date', 'date', 'Bilowga', 'Start date', true),
                zumar_f('end_date', 'date', 'Dhammaadka', 'End date'),
                zumar_f('no_of_participants', 'number', 'Ka-qaybgalayaasha', 'Participants', true),
                zumar_f('female_count', 'number', 'Dumar', 'Female'),
                zumar_f('male_count', 'number', 'Rag', 'Male'),
                zumar_f('completion_rate', 'number', 'Heerka dhammaystirka %', 'Completion rate %'),
            ),
        ),
        'livelihood-assets' => array(
            'table' => 'zf_livelihood_assets',
            'title_so' => 'Qaybinta hantida',
            'title_en' => 'Livelihood asset distribution',
            'icon' => 'fa fa-gift',
            'form_code' => 'LVHD-02',
            'list' => array('beneficiary_name', 'asset_type', 'quantity', 'date_distributed'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('beneficiary_name', 'text', 'Ka-faa\'iidaystaha', 'Beneficiary name', true),
                zumar_f('asset_type', 'select', 'Nooca hantida', 'Asset type', true, array('options' => array('Sewing machine' => 'Sewing machine', 'Cart' => 'Cart', 'Motorcycle' => 'Motorcycle', 'Tractor' => 'Tractor', 'Livestock' => 'Livestock'))),
                zumar_f('quantity', 'number', 'Tirada', 'Quantity', true),
                zumar_f('value_amount', 'money', 'Qiimaha', 'Value'),
                zumar_f('date_distributed', 'date', 'Taariikhda', 'Date distributed', true),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('photo', 'file', 'Sawirka', 'Photo'),
            ),
        ),
        'seed-grants' => array(
            'table' => 'zf_seed_grants',
            'title_so' => 'Deeqaha bilowga',
            'title_en' => 'Startup seed capital grants',
            'icon' => 'fa fa-money',
            'form_code' => 'LVHD-02',
            'list' => array('beneficiary_name', 'business_type', 'amount_granted', 'follow_up_status'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('beneficiary_name', 'text', 'Ka-faa\'iidaystaha', 'Beneficiary name', true),
                zumar_f('business_type', 'text', 'Nooca ganacsiga', 'Business type'),
                zumar_f('amount_granted', 'money', 'Lacagta', 'Amount granted', true),
                zumar_f('training_id', 'fk', 'Tababarkii hore', 'Prior training', false, array('fk' => 'training')),
                zumar_f('disbursement_date', 'date', 'Taariikhda bixinta', 'Disbursement date', true),
                zumar_f('follow_up_status', 'select', 'Xaaladda raadraaca', 'Follow-up status', false, array('options' => array('Business active' => 'Business active', 'Struggling' => 'Struggling', 'Closed' => 'Closed', 'Not yet verified' => 'Not yet verified'))),
            ),
        ),
        'relief-distributions' => array(
            'table' => 'zf_relief_distributions',
            'title_so' => 'Qaybinta gargaarka',
            'title_en' => 'Relief distributions',
            'icon' => 'fa fa-archive',
            'code_field' => 'distribution_code',
            'code_type' => 'relief',
            'form_code' => 'RELF-01',
            'list' => array('distribution_code', 'distribution_type', 'distribution_date', 'no_of_households_reached'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('distribution_type', 'select', 'Nooca', 'Distribution type', true, array('options' => array('Food Package' => 'Food Package', 'Medicine Kit' => 'Medicine Kit', 'Dignity Kit' => 'Dignity Kit', 'Ramadan Giving' => 'Ramadan Giving', 'Qurbani' => 'Qurbani'))),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('distribution_date', 'date', 'Taariikhda', 'Distribution date', true),
                zumar_f('no_of_households_reached', 'number', 'Qoysaska', 'Households reached', true),
                zumar_f('no_of_individuals_reached', 'number', 'Shakhsiyaadka', 'Individuals reached', true),
                zumar_f('items_included', 'textarea', 'Agabka ku jira', 'Items included'),
                zumar_f('unit_cost_per_package', 'money', 'Qiimaha xirmada', 'Unit cost per package'),
                zumar_f('photos', 'file', 'Sawirada', 'Photos'),
                zumar_f('distributed_by', 'fk', 'Qaybiyay', 'Distributed by', true, array('fk' => 'staff')),
            ),
        ),
        'mediation-cases' => array(
            'table' => 'zf_mediation_cases',
            'title_so' => 'Kiisaska dhexdhexaadinta',
            'title_en' => 'Mediation cases',
            'icon' => 'fa fa-balance-scale',
            'code_field' => 'case_code',
            'code_type' => 'mediation',
            'form_code' => 'PEACE-01',
            'restricted' => true,
            'list' => array('case_code', 'case_type', 'date_opened', 'case_status'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('case_type', 'select', 'Nooca kiiska', 'Case type', true, array('options' => array('Land dispute' => 'Land dispute', 'Clan conflict' => 'Clan conflict', 'Family/community dispute' => 'Family/community dispute', 'Resource conflict' => 'Resource conflict'))),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('date_opened', 'date', 'Taariikhda furitaanka', 'Date opened', true),
                zumar_f('parties_involved', 'text', 'Dhinacyada', 'Parties involved'),
                zumar_f('mediator_id', 'fk', 'Dhexdhexaadiyaha', 'Mediator', true, array('fk' => 'staff')),
                zumar_f('sessions_held', 'number', 'Kulammada', 'Sessions held'),
                zumar_f('case_status', 'select', 'Xaaladda', 'Case status', true, array('options' => array('Open' => 'Open', 'Resolved' => 'Resolved', 'Escalated' => 'Escalated', 'Closed unresolved' => 'Closed unresolved'))),
                zumar_f('resolution_date', 'date', 'Taariikhda xallinta', 'Resolution date'),
                zumar_f('outcome_summary', 'textarea', 'Natiijada', 'Outcome summary'),
            ),
        ),
        'dialogue-sessions' => array(
            'table' => 'zf_dialogue_sessions',
            'title_so' => 'Wadahadallada',
            'title_en' => 'Dialogue sessions',
            'icon' => 'fa fa-comments',
            'form_code' => 'PEACE-02',
            'list' => array('session_topic', 'session_date', 'no_of_participants'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('session_topic', 'text', 'Mawduuca', 'Session topic', true),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('session_date', 'date', 'Taariikhda', 'Session date', true),
                zumar_f('groups_represented', 'text', 'Kooxaha', 'Groups represented'),
                zumar_f('no_of_participants', 'number', 'Ka-qaybgalayaasha', 'Participants', true),
                zumar_f('female_count', 'number', 'Dumar', 'Female'),
                zumar_f('male_count', 'number', 'Rag', 'Male'),
                zumar_f('facilitator_id', 'fk', 'Fududeeyaha', 'Facilitator', true, array('fk' => 'staff')),
                zumar_f('key_outcomes', 'textarea', 'Natiijooyinka', 'Key outcomes'),
            ),
        ),
        'legal-aid' => array(
            'table' => 'zf_legal_aid',
            'title_so' => 'Kaalmada sharciga',
            'title_en' => 'Legal aid cases',
            'icon' => 'fa fa-gavel',
            'restricted' => true,
            'list' => array('case_nature', 'date_opened', 'case_status', 'vulnerability_category'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('beneficiary_name', 'text', 'Ka-faa\'iidaystaha', 'Beneficiary name', true),
                zumar_f('vulnerability_category', 'select', 'Nooca nuglaanta', 'Vulnerability category', false, array('options' => array('GBV survivor' => 'GBV survivor', 'Displaced person' => 'Displaced person', 'Minor' => 'Minor', 'Other' => 'Other'))),
                zumar_f('case_nature', 'text', 'Dabeecadda kiiska', 'Case nature', true),
                zumar_f('date_opened', 'date', 'Taariikhda furitaanka', 'Date opened', true),
                zumar_f('legal_aid_provider', 'text', 'Bixiyaha kaalmada', 'Legal aid provider', true),
                zumar_f('case_status', 'select', 'Xaaladda', 'Case status', true, array('options' => array('Ongoing' => 'Ongoing', 'Resolved' => 'Resolved', 'Referred' => 'Referred', 'Closed' => 'Closed'))),
                zumar_f('referral_institution', 'text', 'Hay\'adda loo gudbiyay', 'Referral institution'),
            ),
        ),
        'budgets' => array(
            'table' => 'zf_budgets',
            'title_so' => 'Miisaaniyadaha',
            'title_en' => 'Budgets',
            'icon' => 'fa fa-calculator',
            'list' => array('project_id', 'budget_line', 'budgeted_amount', 'currency', 'budget_period'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('budget_line', 'text', 'Qadka miisaaniyadda', 'Budget line', true),
                zumar_f('budgeted_amount', 'money', 'Lacagta', 'Budgeted amount', true),
                zumar_f('currency', 'text', 'Lacagta', 'Currency', true),
                zumar_f('budget_period', 'text', 'Mudada', 'Budget period', true),
            ),
        ),
        'expenses' => array(
            'table' => 'zf_expenses',
            'title_so' => 'Kharashyada',
            'title_en' => 'Expenses',
            'icon' => 'fa fa-credit-card',
            'list' => array('project_id', 'expense_date', 'amount', 'expense_category'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('budget_id', 'fk', 'Miisaaniyadda', 'Budget', false, array('fk' => 'budget')),
                zumar_f('expense_date', 'date', 'Taariikhda', 'Expense date', true),
                zumar_f('amount', 'money', 'Lacagta', 'Amount', true),
                zumar_f('expense_category', 'select', 'Qaybta', 'Expense category', true, array('options' => array('Staff' => 'Staff', 'Materials' => 'Materials', 'Transport' => 'Transport', 'Utilities' => 'Utilities', 'Other' => 'Other'))),
                zumar_f('linked_module_record', 'text', 'Diiwaanka la xiriira', 'Linked module record'),
                zumar_f('approved_by', 'fk', 'Ansixiyay', 'Approved by', true, array('fk' => 'staff')),
                zumar_f('receipt_attached', 'file', 'Rasiidka', 'Receipt'),
            ),
        ),
        'donor-funding' => array(
            'table' => 'zf_donor_funding',
            'title_so' => 'Maalgelinta deeq-bixiyayaasha',
            'title_en' => 'Donor funding',
            'icon' => 'fa fa-university',
            'list' => array('project_id', 'partner_id', 'amount_committed', 'amount_received'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('partner_id', 'fk', 'Lammaanaha', 'Partner', true, array('fk' => 'partner')),
                zumar_f('amount_committed', 'money', 'Lacagta la ballanqaaday', 'Amount committed', true),
                zumar_f('amount_received', 'money', 'Lacagta la helay', 'Amount received'),
                zumar_f('agreement_reference', 'text', 'Tixraaca heshiiska', 'Agreement reference'),
            ),
        ),
        'disbursements' => array(
            'table' => 'zf_disbursements',
            'title_so' => 'Bixinta lacagta',
            'title_en' => 'Disbursements',
            'icon' => 'fa fa-exchange',
            'list' => array('project_id', 'recipient_type', 'amount', 'disbursement_date', 'method'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('recipient_type', 'select', 'Nooca qaataha', 'Recipient type', true, array('options' => array('Beneficiary' => 'Beneficiary', 'Vendor' => 'Vendor', 'Staff' => 'Staff', 'Implementing Partner' => 'Implementing Partner'))),
                zumar_f('recipient_reference', 'text', 'Tixraaca qaataha', 'Recipient reference', true),
                zumar_f('amount', 'money', 'Lacagta', 'Amount', true),
                zumar_f('disbursement_date', 'date', 'Taariikhda', 'Disbursement date', true),
                zumar_f('method', 'select', 'Habka', 'Method', false, array('options' => array('Cash' => 'Cash', 'Mobile money' => 'Mobile money', 'Bank transfer' => 'Bank transfer'))),
            ),
        ),
        'staff-assignments' => array(
            'table' => 'zf_staff_assignments',
            'title_so' => 'Qoondeynta mashruuca',
            'title_en' => 'Staff project assignments',
            'icon' => 'fa fa-sitemap',
            'list' => array('staff_id', 'project_id', 'role_on_project', 'allocation_percentage'),
            'fields' => array(
                zumar_f('staff_id', 'fk', 'Shaqaalaha', 'Staff', true, array('fk' => 'staff')),
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('role_on_project', 'text', 'Doorka mashruuca', 'Role on project', true),
                zumar_f('allocation_percentage', 'number', 'Boqolleyda waqtiga', 'Allocation %'),
                zumar_f('start_date', 'date', 'Bilowga', 'Start date'),
                zumar_f('end_date', 'date', 'Dhammaadka', 'End date'),
            ),
        ),
        'recruitments' => array(
            'table' => 'zf_recruitments',
            'title_so' => 'Shaqo-qorista',
            'title_en' => 'Recruitment',
            'icon' => 'fa fa-briefcase',
            'list' => array('position_title', 'project_id', 'status'),
            'fields' => array(
                zumar_f('position_title', 'text', 'Jagada', 'Position title', true),
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', false, array('fk' => 'project')),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Open' => 'Open', 'Shortlisting' => 'Shortlisting', 'Filled' => 'Filled', 'Cancelled' => 'Cancelled'))),
            ),
        ),
        'policy-acknowledgements' => array(
            'table' => 'zf_policy_acks',
            'title_so' => 'Oggolaanshaha siyaasadaha',
            'title_en' => 'Policy acknowledgements',
            'icon' => 'fa fa-file-text',
            'list' => array('staff_id', 'policy_name', 'date_acknowledged'),
            'fields' => array(
                zumar_f('staff_id', 'fk', 'Shaqaalaha', 'Staff', true, array('fk' => 'staff')),
                zumar_f('policy_name', 'fk', 'Siyaasadda', 'Policy name', true, array('fk' => 'policy')),
                zumar_f('date_acknowledged', 'date', 'Taariikhda', 'Date acknowledged', true),
                zumar_f('signed_document', 'file', 'Dokumentiga saxeexan', 'Signed document'),
            ),
        ),
        'vendors' => array(
            'table' => 'zf_vendors',
            'title_so' => 'Iibiyayaasha',
            'title_en' => 'Vendors',
            'icon' => 'fa fa-truck',
            'list' => array('vendor_name', 'country_code', 'category', 'vetting_status'),
            'fields' => array(
                zumar_f('vendor_name', 'text', 'Magaca', 'Vendor name', true),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('category', 'select', 'Qaybta', 'Category', false, array('options' => array('Construction' => 'Construction', 'Medical supplies' => 'Medical supplies', 'Food' => 'Food', 'Stationery' => 'Stationery', 'Other' => 'Other'))),
                zumar_f('contact_info', 'text', 'Xiriirka', 'Contact info'),
                zumar_f('vetting_status', 'select', 'Xaaladda baaritaanka', 'Vetting status', true, array('options' => array('Approved' => 'Approved', 'Pending' => 'Pending', 'Blacklisted' => 'Blacklisted'))),
            ),
        ),
        'purchase-requests' => array(
            'table' => 'zf_purchase_requests',
            'title_so' => 'Codsiyada iibsiga',
            'title_en' => 'Purchase requests',
            'icon' => 'fa fa-file-o',
            'list' => array('id', 'project_id', 'date_requested', 'approval_status'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('requested_by', 'fk', 'Codsaday', 'Requested by', true, array('fk' => 'staff')),
                zumar_f('items_requested', 'textarea', 'Alaabta la codsaday', 'Items requested', true),
                zumar_f('date_requested', 'date', 'Taariikhda', 'Date requested', true),
                zumar_f('approval_status', 'select', 'Ansixinta', 'Approval status', true, array('options' => array('Pending' => 'Pending', 'Approved by Operations Manager' => 'Approved by Operations Manager', 'Rejected' => 'Rejected'))),
            ),
        ),
        'purchase-orders' => array(
            'table' => 'zf_purchase_orders',
            'title_so' => 'Amarada iibsiga',
            'title_en' => 'Purchase orders',
            'icon' => 'fa fa-file-text-o',
            'list' => array('id', 'pr_id', 'vendor_id', 'total_amount', 'delivery_status'),
            'fields' => array(
                zumar_f('pr_id', 'fk', 'Codsiga iibsiga', 'Purchase request', true, array('fk' => 'pr')),
                zumar_f('vendor_id', 'fk', 'Iibiyaha', 'Vendor', true, array('fk' => 'vendor')),
                zumar_f('total_amount', 'money', 'Wadarta', 'Total amount', true),
                zumar_f('po_date', 'date', 'Taariikhda PO', 'PO date', true),
                zumar_f('delivery_status', 'select', 'Xaaladda gaarsiinta', 'Delivery status', true, array('options' => array('Pending' => 'Pending', 'Partially delivered' => 'Partially delivered', 'Delivered' => 'Delivered'))),
            ),
        ),
        'goods-received' => array(
            'table' => 'zf_goods_received',
            'title_so' => 'Alaabta la helay',
            'title_en' => 'Goods received notes',
            'icon' => 'fa fa-check-square',
            'list' => array('po_id', 'received_date', 'received_by'),
            'fields' => array(
                zumar_f('po_id', 'fk', 'Amarka iibsiga', 'Purchase order', true, array('fk' => 'po')),
                zumar_f('received_date', 'date', 'Taariikhda helitaanka', 'Received date', true),
                zumar_f('received_by', 'fk', 'Helay', 'Received by', true, array('fk' => 'staff')),
                zumar_f('condition_notes', 'textarea', 'Xaaladda', 'Condition notes'),
                zumar_f('linked_distribution_record', 'text', 'Diiwaanka qaybinta', 'Linked distribution record'),
            ),
        ),
        'indicators' => array(
            'table' => 'zf_indicators',
            'title_so' => 'Tilmaamayaasha',
            'title_en' => 'Indicators',
            'icon' => 'fa fa-line-chart',
            'list' => array('project_id', 'indicator_name', 'target_value', 'achieved_value', 'measurement_frequency'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('indicator_name', 'text', 'Magaca tilmaamaha', 'Indicator name', true),
                zumar_f('target_value', 'number', 'Bartilmaameedka', 'Target value', true),
                zumar_f('achieved_value', 'number', 'La gaaray', 'Achieved value'),
                zumar_f('measurement_frequency', 'select', 'Inta jeer', 'Frequency', true, array('options' => array('Monthly' => 'Monthly', 'Quarterly' => 'Quarterly', 'Annual' => 'Annual'))),
            ),
        ),
        'monitoring-visits' => array(
            'table' => 'zf_monitoring_visits',
            'title_so' => 'Boqashooyinka kormeerka',
            'title_en' => 'Monitoring visits',
            'icon' => 'fa fa-map',
            'list' => array('project_id', 'visit_date', 'conducted_by'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('visit_date', 'date', 'Taariikhda', 'Visit date', true),
                zumar_f('conducted_by', 'fk', 'Sameeyay', 'Conducted by', true, array('fk' => 'staff')),
                zumar_f('location_id', 'fk', 'Goobta', 'Location', true, array('fk' => 'location')),
                zumar_f('findings_summary', 'textarea', 'Natiijooyinka', 'Findings summary', true),
                zumar_f('follow_up_actions', 'textarea', 'Tallaabooyinka raadraaca', 'Follow-up actions'),
            ),
        ),
        'evaluations' => array(
            'table' => 'zf_evaluations',
            'title_so' => 'Qiimaynta',
            'title_en' => 'Evaluations',
            'icon' => 'fa fa-bar-chart',
            'list' => array('project_id', 'evaluation_type', 'conducted_by', 'date_completed'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', true, array('fk' => 'project')),
                zumar_f('evaluation_type', 'select', 'Nooca', 'Evaluation type', true, array('options' => array('Baseline' => 'Baseline', 'Midline' => 'Midline', 'Endline' => 'Endline', 'Ad-hoc' => 'Ad-hoc'))),
                zumar_f('conducted_by', 'text', 'Sameeyay', 'Conducted by', true),
                zumar_f('date_completed', 'date', 'Taariikhda', 'Date completed', true),
                zumar_f('report_file', 'file', 'Warbixinta', 'Report file'),
            ),
        ),
        'complaints' => array(
            'table' => 'zf_complaints',
            'title_so' => 'Cabashooyinka',
            'title_en' => 'Complaints & feedback',
            'icon' => 'fa fa-commenting',
            'restricted' => true,
            'list' => array('date_received', 'channel', 'category', 'status', 'confidentiality_flag'),
            'fields' => array(
                zumar_f('project_id', 'fk', 'Mashruuca', 'Project', false, array('fk' => 'project')),
                zumar_f('date_received', 'date', 'Taariikhda', 'Date received', true),
                zumar_f('channel', 'select', 'Kanaalka', 'Channel', true, array('options' => array('Hotline' => 'Hotline', 'In-person' => 'In-person', 'Suggestion box' => 'Suggestion box', 'Community meeting' => 'Community meeting'))),
                zumar_f('category', 'select', 'Qaybta', 'Category', true, array('options' => array('Program quality' => 'Program quality', 'Staff conduct' => 'Staff conduct', 'Safeguarding concern' => 'Safeguarding concern', 'Other' => 'Other'))),
                zumar_f('status', 'select', 'Xaaladda', 'Status', true, array('options' => array('Open' => 'Open', 'Under investigation' => 'Under investigation', 'Resolved' => 'Resolved', 'Escalated' => 'Escalated'))),
                zumar_f('confidentiality_flag', 'select', 'Qarsoodi', 'Confidentiality', true, array('options' => $yesNo)),
                zumar_f('details', 'textarea', 'Faahfaahin', 'Details'),
            ),
        ),
        'research-studies' => array(
            'table' => 'zf_research_studies',
            'title_so' => 'Daraasado & baaritaan',
            'title_en' => 'Needs assessments & studies',
            'icon' => 'fa fa-search',
            'list' => array('study_title', 'study_type', 'country_code', 'date_conducted'),
            'fields' => array(
                zumar_f('related_sector', 'fk', 'Qaybta', 'Related sector', false, array('fk' => 'sector')),
                zumar_f('country_code', 'fk', 'Waddanka', 'Country', true, array('fk' => 'country')),
                zumar_f('study_title', 'text', 'Cinwaanka', 'Study title', true),
                zumar_f('study_type', 'select', 'Nooca', 'Study type', true, array('options' => array('Needs assessment' => 'Needs assessment', 'Baseline study' => 'Baseline study', 'Thematic research' => 'Thematic research'))),
                zumar_f('date_conducted', 'date', 'Taariikhda', 'Date conducted', true),
                zumar_f('sample_size', 'number', 'Cabbirka muunada', 'Sample size'),
                zumar_f('key_findings_summary', 'textarea', 'Natiijooyinka', 'Key findings'),
                zumar_f('report_file', 'file', 'Warbixinta', 'Report file'),
                zumar_f('informs_project_id', 'fk', 'Mashruuca uu saameeyay', 'Informs project', false, array('fk' => 'project')),
            ),
        ),
    );

    return $modules;
}

function zumar_module($key)
{
    $all = zumar_modules();
    return $all[$key] ?? null;
}
